services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
        # creer un utilisateur username023 avec le mot de passe password023
        POSTGRES_USER: username023
        POSTGRES_PASSWORD: password023
        # creer un volume pour stocker les donnees de la base de donnee
        PGDATA: /var/lib/postgresql/data
        # creer une base de donnee book_social
        POSTGRES_DB: book_social

    ports:
      - 5432:5432

    restart: unless-stopped

  maildev:
    container_name: mail-dev-social
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

